function(_elfconv_json_escape input output)
  set(value "${input}")
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(_elfconv_mount_path mount_prefix relative_path output)
  if(mount_prefix STREQUAL "/")
    set(path "/${relative_path}")
  else()
    set(path "${mount_prefix}/${relative_path}")
  endif()
  set(${output} "${path}" PARENT_SCOPE)
endfunction()

function(elfconv_pack_preload mount_specs output_dir)
  file(MAKE_DIRECTORY "${output_dir}")
  set(manifest_entries "")

  foreach(spec IN LISTS mount_specs)
    if(NOT spec MATCHES "^(.+)@(/.*)$")
      message(FATAL_ERROR "Invalid preload mount spec '${spec}'; expected host_dir@/mount/path")
    endif()
    set(host_dir "${CMAKE_MATCH_1}")
    set(mount_point "${CMAKE_MATCH_2}")
    if(NOT IS_DIRECTORY "${host_dir}")
      message(FATAL_ERROR "Preload host directory not found: ${host_dir}")
    endif()
    file(REAL_PATH "${host_dir}" host_dir)
    string(REGEX REPLACE "/+$" "" mount_prefix "${mount_point}")
    if(mount_prefix STREQUAL "")
      set(mount_prefix "/")
    endif()

    string(REGEX REPLACE "^/+" "" data_stem "${mount_point}")
    string(REGEX REPLACE "/+$" "" data_stem "${data_stem}")
    string(REPLACE "/" "_" data_stem "${data_stem}")
    set(data_name "${data_stem}.data")
    set(data_path "${output_dir}/${data_name}")

    file(GLOB_RECURSE relative_files LIST_DIRECTORIES false RELATIVE "${host_dir}" "${host_dir}/*")
    list(SORT relative_files)
    set(file_mount_paths)
    set(file_hosts)
    foreach(relative_path IN LISTS relative_files)
      if(relative_path MATCHES "(^|/)\\.[^/]*")
        continue()
      endif()
      set(host_path "${host_dir}/${relative_path}")
      if(IS_DIRECTORY "${host_path}" OR NOT EXISTS "${host_path}")
        continue()
      endif()
      _elfconv_mount_path("${mount_prefix}" "${relative_path}" mount_path)
      list(APPEND file_mount_paths "${mount_path}")
      list(APPEND file_hosts "${host_path}")
    endforeach()

    file(GLOB_RECURSE relative_dirs LIST_DIRECTORIES true RELATIVE "${host_dir}" "${host_dir}/*")
    set(directories)
    if(NOT mount_prefix STREQUAL "/")
      list(APPEND directories "${mount_prefix}")
    endif()
    foreach(relative_path IN LISTS relative_dirs)
      if(relative_path MATCHES "(^|/)\\.[^/]*" OR NOT IS_DIRECTORY "${host_dir}/${relative_path}")
        continue()
      endif()
      _elfconv_mount_path("${mount_prefix}" "${relative_path}" mount_dir)
      list(APPEND directories "${mount_dir}")
    endforeach()
    set(all_directories ${directories})
    foreach(directory IN LISTS directories)
      set(parent "${directory}")
      while(NOT parent STREQUAL "/" AND NOT parent STREQUAL "")
        list(APPEND all_directories "${parent}")
        cmake_path(GET parent PARENT_PATH parent)
        if(parent STREQUAL "")
          set(parent "/")
        endif()
      endwhile()
    endforeach()
    list(REMOVE_DUPLICATES all_directories)
    list(SORT all_directories)

    if(NOT file_hosts AND NOT all_directories)
      message(WARNING "No files or directories found under ${host_dir} for mount ${mount_point}")
      continue()
    endif()

    if(file_hosts)
      execute_process(
        COMMAND "${CMAKE_COMMAND}" -E cat ${file_hosts}
        OUTPUT_FILE "${data_path}"
        RESULT_VARIABLE cat_result
        ERROR_VARIABLE cat_error
      )
      if(NOT cat_result EQUAL 0)
        message(FATAL_ERROR "Could not pack preload data ${data_path}: ${cat_error}")
      endif()
    else()
      file(WRITE "${data_path}" "")
    endif()

    set(files_json "")
    set(offset 0)
    list(LENGTH file_hosts file_count)
    if(file_count GREATER 0)
      math(EXPR last_file "${file_count} - 1")
      foreach(index RANGE 0 ${last_file})
        list(GET file_hosts ${index} host_path)
        list(GET file_mount_paths ${index} mount_path)
        file(SIZE "${host_path}" size)
        math(EXPR end_offset "${offset} + ${size}")
        _elfconv_json_escape("${mount_path}" escaped_mount_path)
        if(NOT files_json STREQUAL "")
          string(APPEND files_json ",")
        endif()
        string(APPEND files_json "{\"filename\":\"${escaped_mount_path}\",\"start\":${offset},\"end\":${end_offset}}")
        set(offset "${end_offset}")
      endforeach()
    endif()

    set(directories_json "")
    foreach(directory IN LISTS all_directories)
      _elfconv_json_escape("${directory}" escaped_directory)
      if(NOT directories_json STREQUAL "")
        string(APPEND directories_json ",")
      endif()
      string(APPEND directories_json "\"${escaped_directory}\"")
    endforeach()
    _elfconv_json_escape("${data_name}" escaped_data_name)
    if(NOT manifest_entries STREQUAL "")
      string(APPEND manifest_entries ",")
    endif()
    string(APPEND manifest_entries "{\"packageDataName\":\"${escaped_data_name}\",\"remote_package_size\":${offset},\"directories\":[${directories_json}],\"files\":[${files_json}]}")
    list(LENGTH all_directories directory_count)
    message(STATUS "Packed ${file_count} files and ${directory_count} directories (${offset} bytes) into ${data_path}")
  endforeach()

  file(WRITE "${output_dir}/preload-manifest.json" "[${manifest_entries}]\n")
endfunction()
if(ELFCONV_PACK_PRELOAD_ONLY)
  if(NOT DEFINED ELFCONV_MOUNT_SETTINGS OR NOT DEFINED ELFCONV_OUTPUT_DIR)
    message(FATAL_ERROR "Preload packaging requires ELFCONV_MOUNT_SETTINGS and ELFCONV_OUTPUT_DIR")
  endif()
  elfconv_pack_preload("${ELFCONV_MOUNT_SETTINGS}" "${ELFCONV_OUTPUT_DIR}")
endif()
